
name: Publish

# Trigger the create release workflow
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"
      - name: Build with Gradle
        run: ./gradlew build --no-daemon -x test
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /@(spigot|velocity|api)/build/libs/*
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
          body: "Release ${{ github.ref }}"
